FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY celery_req.txt ./
RUN pip install --no-cache-dir -r celery_req.txt

COPY . .

CMD ["celery", "-A", "Celery_worker.config:celery_app", "worker", "--loglevel=info"]